# Generated by Django 3.2 on 2021-04-13 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbax', '0012_auto_20210413_0440'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nyumbax.hood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to=settings.AUTH_USER_MODEL),
        ),
    ]
