# Generated by Django 3.2 on 2021-04-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbax', '0003_hood_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='hood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyumbax.hood'),
            preserve_default=False,
        ),
    ]
