# Generated by Django 3.2 on 2021-04-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbax', '0004_essential_hood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='essential',
            name='hood',
        ),
        migrations.AddField(
            model_name='essential',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyumbax.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hood',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyumbax.location'),
        ),
    ]
