# Generated by Django 3.2 on 2021-04-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbax', '0006_auto_20210411_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyumbax.hood'),
            preserve_default=False,
        ),
    ]
