# Generated by Django 3.2 on 2021-04-12 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nyumbax', '0007_post_hood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nyumbax.hood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hood',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
