# Generated by Django 3.2 on 2021-04-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbax', '0010_remove_hood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyumbax.hood'),
        ),
    ]
