# Generated by Django 3.2 on 2021-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbax', '0013_auto_20210413_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
