# Generated by Django 3.2 on 2021-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumbax', '0014_alter_business_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='body',
            field=models.TextField(),
        ),
    ]
